### ISSUE TITLE
tkinter exception thrown in example code

### ISSUE THREAD

**Issue by bmosley** [erivlis/graphinate#13]
I've installed the latest tkinter and graphinate today and hitting an exception on the demo code already. I did not install the server (which i thought was optional)

Python 3.10.12 / Linux Mint
https://erivlis.github.io/graphinate/start/

```
$  /home/bmo/code/graphinate/env/bin/python /home/bmosley/code/graphinate/graph_fun.py                                                                                                              exit 1
Traceback (most recent call last):
  File "/home/bmo/code/graphinate/graph_fun.py", line 18, in <module>
    graphinate.materialize(graph_model)
  File "/home/bmo/code/graphinate/env/lib/python3.10/site-packages/graphinate/materializers/__init__.py", line 54, in materialize
    result = modal_radiobutton_chooser(title,
  File "/home/bmo/code/graphinate/env/lib/python3.10/site-packages/graphinate/tools/gui.py", line 18, in modal_radiobutton_chooser
    win = _modal_window(window_title)
  File "/home/bmo/code/graphinate/env/lib/python3.10/site-packages/graphinate/tools/gui.py", line 10, in _modal_window
    win.wm_attributes('-toolwindow', 'True')
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-toolwindow": must be -alpha, -topmost, -zoomed, -fullscreen, or -type

**Comment by erivlis** [comment]
@bmosley Please try Graphinate 0.2.8
